# Generated by Django 3.2.6 on 2021-09-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Content',
            field=models.TextField(null=True, verbose_name='内容'),
        ),
    ]
