# Generated by Django 3.2.6 on 2021-10-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_news_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=60, verbose_name='类别')),
                ('Name', models.CharField(max_length=20, verbose_name='名称')),
                ('Must', models.TextField(null=True, verbose_name='必要性')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('Unit', models.CharField(max_length=10, verbose_name='单位')),
                ('createdtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedtime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('Memo', models.TextField(null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '服务价目表',
            },
        ),
    ]
