# Generated by Django 3.2.6 on 2021-10-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='service',
            name='Must',
            field=models.CharField(choices=[('必选', '必选'), ('可选', '可选')], max_length=10, verbose_name='必要性'),
        ),
    ]
