# Generated by Django 3.2.6 on 2021-10-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20211008_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Must',
            field=models.CharField(choices=[('Phone', 'Phone'), ('PBX', 'PBX'), ('Number', 'Number')], max_length=10, verbose_name='必要性'),
        ),
        migrations.AlterField(
            model_name='service',
            name='Type',
            field=models.CharField(blank=True, choices=[('Phone', 'Phone'), ('PBX', 'PBX'), ('Number', 'Number')], max_length=60, null=True, verbose_name='类别'),
        ),
    ]
