# Generated by Django 3.2.6 on 2021-10-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_service_must'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Unit',
            field=models.CharField(choices=[('元/月.个', '元/月.个'), ('元/月.套', '元/月.套'), ('元/月.号', '元/月.号'), ('元/月.线', '元/月.线'), ('元/分钟', '元/分钟')], max_length=10, verbose_name='单位'),
        ),
    ]
