# Generated by Django 3.2.6 on 2021-10-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_service_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='idx',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='顺序'),
        ),
    ]
