# Generated by Django 3.2.6 on 2021-10-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_service_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='idx',
            field=models.IntegerField(blank=True, null=True, verbose_name='顺序'),
        ),
    ]
