# Generated by Django 3.2.6 on 2021-10-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_service_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True, verbose_name='园区名称')),
                ('Address', models.CharField(blank=True, max_length=50, null=True, verbose_name='地址')),
                ('Level', models.CharField(blank=True, choices=[('A类园区', 'A类园区'), ('B类园区', 'B类园区'), ('C类园区', 'C类园区'), ('D类园区', 'D类园区')], max_length=60, null=True, verbose_name='类别')),
                ('Province', models.CharField(blank=True, max_length=30, null=True, verbose_name='省份')),
                ('City', models.CharField(blank=True, max_length=30, null=True, verbose_name='城市')),
                ('District', models.CharField(blank=True, max_length=30, null=True, verbose_name='区县')),
                ('Town', models.CharField(blank=True, max_length=30, null=True, verbose_name='乡镇')),
                ('createdtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatedtime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('Memo', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '园区',
            },
        ),
    ]
