# Generated by Django 3.2.6 on 2021-10-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_park'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='Manager',
            field=models.CharField(blank=True, choices=[('沈承永', '沈承永'), ('张浩', '张浩')], max_length=60, null=True, verbose_name='园区经理'),
        ),
        migrations.AlterField(
            model_name='park',
            name='Level',
            field=models.CharField(blank=True, choices=[('A、物业可办理', 'A、物业可办理'), ('B、有客户', 'B、有客户'), ('C、4小时开通', 'C、4小时开通'), ('D、24小时上门', 'D、24小时开通')], max_length=60, null=True, verbose_name='类别'),
        ),
    ]
